version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/movement-db
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            # Add other environment variables as needed from .env.local
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - db
            - redis
        restart: unless-stopped
        command: npm run dev

    db:
        image: postgres:16-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=movement-db
        volumes:
            - postgres_data_dev:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data_dev:
